fix: runner/module resolution logic
hugomrdias/playwright-test pull request #562
Opened 2023-07-06 18:43 UTC by Gozala

fixes #561

2023-07-06 19:10 UTC, Gozala commented on src/utils/index.js
> +import { fileURLToPath } from 'url'
```suggestion
import { fileURLToPath, pathToFileURL } from 'url'
```

2023-07-06 19:11 UTC, Gozala commented on src/utils/index.js
> +    return await import(createRequire(toDirectoryPath(base)).resolve(id))
```suggestion
    const path = createRequire(toDirectoryPath(base)).resolve(id)
    const url = pathToFileURL(path)
    return await import(url)
```

2023-07-06 19:35 UTC, Gozala commented on src/utils/index.js
> +    return await import(url)
```suggestion
    return await import(url.href)
```

2023-07-06 20:25 UTC, Gozala commented
cc @hugomrdias as I'm unable to add you as a reviewer

2023-07-06 21:47 UTC, hugomrdias requested changes
theres 2 path here, either a module id or a path (relative or absolute) you version does not import from a module export path ie. <module/id>/<export>

in you case it seems you are in the test runner repo, so you need to use path version because `entail` is not in node_modules.

2023-07-06 22:35 UTC, Gozala commented
> in you case it seems you are in the test runner repo, so you need to use path version because `entail` is not in node_modules.

I am pretty sure that is not the problem (I can verify if you want me to), problem is that on line 512 import will be resolved from `playwright-test/src/utils/index.js` path not from my package path and depending on where playwright-test is that may fail. E.g. if I do `npx playwright-test` it will end up in a entire different path than my package or it's dependencies

https://github.com/hugomrdias/playwright-test/blob/2d1c32deef36a80a1cf2bff13cc0617b477a6a9c/src/utils/index.js#L509-L528

2023-07-06 22:45 UTC, Gozala commented
Here is the example illustrating my point above

```
pnpm test:web                                              ✭

> sync-multihash-sha2@1.0.0 test:web /Users/gozala/Projects/sha256-multihash
> npx playwright-test test --runner entail test/*.js --cov && nyc report

Error: Cannot resolve module "entail" from "/Users/gozala/Projects/sha256-multihash"
    at resolveModule (file:///Users/gozala/.npm/_npx/2c2b474230005785/node_modules/playwright-test/src/utils/index.js:524:11)
    at async resolveTestRunner (file:///Users/gozala/.npm/_npx/2c2b474230005785/node_modules/playwright-test/src/utils/index.js:544:18)
    at async file:///Users/gozala/.npm/_npx/2c2b474230005785/node_modules/playwright-test/cli.js:273:34
 ELIFECYCLE  Command failed with exit code 1.
```

You can find source here https://github.com/web3-storage/sync-multihash-sha2/pull/3

2023-07-07 11:40 UTC, hugomrdias approved these changes

2023-07-07 11:40 UTC, hugomrdias commented on src/utils/index.js
> +    // last entry is gonig to be dropped during resolution.
```suggestion
    // last entry is going to be dropped during resolution.
```

2023-07-07 11:44 UTC, merged